"use client";
import { useMemo,useState,useTransition } from "react";
import { ArrowLeft,ArrowRight,ArrowUpDown,Grid3X3,Pencil,Plus,Search,Trash2,X } from "lucide-react";
import { deleteSubjectAction,saveSubjectAction } from "@/app/actions";
type Career={id:number;acronym:string;name:string}; type Subject={id:number;code:string;name:string;coordination:string;semester:number;careers:Career[]};
const blank={id:0,code:"",name:"",coordination:"Coordinación",semester:1,careerIds:[] as number[]};
export function SubjectsManager({subjects,careers}:{subjects:Subject[];careers:Career[]}){
 const [mode,setMode]=useState<"add"|"edit"|"delete"|null>(null),[form,setForm]=useState(blank),[multi,setMulti]=useState(false),[search,setSearch]=useState(""); const [pending,start]=useTransition();
 const selected=useMemo(()=>subjects.find(s=>s.id===form.id),[subjects,form.id]); const rows=subjects.filter(s=>(s.code+" "+s.name).toLowerCase().includes(search.toLowerCase()));
 const edit=(s:Subject)=>{setForm({id:s.id,code:s.code,name:s.name,coordination:s.coordination,semester:s.semester,careerIds:s.careers.map(c=>c.id)});setMode("edit")};
 const toggle=(id:number)=>setForm({...form,careerIds:form.careerIds.includes(id)?form.careerIds.filter(x=>x!==id):[...form.careerIds,id]});
 const save=()=>start(async()=>{const fd=new FormData();if(form.id)fd.set("id",String(form.id));fd.set("code",form.code);fd.set("name",form.name);fd.set("coordination",form.coordination);fd.set("semester",String(form.semester));form.careerIds.forEach(id=>fd.append("careerIds",String(id)));await saveSubjectAction(fd);setMode(null)});
 const remove=()=>start(async()=>{const fd=new FormData();fd.set("id",String(form.id));await deleteSubjectAction(fd);setMode(null)});
 return <div className="crud-page"><section className="table-card subject-card"><div className="subject-heading"><div><h2>Materias registradas</h2><p>Cantidad de materias: {subjects.length}</p></div><button className="round-add" onClick={()=>{setForm({...blank,careerIds:careers[0]?[careers[0].id]:[]});setMode("add")}}><Plus/></button></div><div className="filters-row"><div className="filter-group"><select><option>Coordinación</option></select><select><option>Carrera</option></select><select><option>Semestre</option></select></div><label className="search-box"><Search size={15}/><input placeholder="Buscar materia..." value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="table-scroll"><table><thead><tr><th><ArrowUpDown size={12}/> Clave</th><th><ArrowUpDown size={12}/> Nombre</th><th><ArrowUpDown size={12}/> Coordinación</th><th>Carrera</th><th><ArrowUpDown size={12}/> Semestre</th><th>Acciones</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.code}</td><td>{s.name}</td><td>{s.coordination}</td><td><div className="pill-list">{s.careers.map(c=><span className="career-pill" key={c.id}>{c.acronym}</span>)}</div></td><td>{s.semester}to</td><td><div className="crud-actions"><button className="edit-btn" onClick={()=>edit(s)}><Pencil size={17}/></button><button className="delete-btn" onClick={()=>{setForm({...blank,id:s.id});setMode("delete")}}><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div><div className="pagination"><button><ArrowLeft size={18}/></button><button><ArrowRight size={18}/></button></div></section>
 {mode&&<div className="modal-backdrop"><div className={`modal crud-modal subject-modal ${mode==="delete"?"confirm-modal":""}`}>{mode==="delete"?<><h2>Eliminar materia</h2><p>¿Estas seguro de eliminar la materia?</p><strong className="confirm-name">Materia: {selected?.name}</strong><div className="confirm-actions"><button className="danger-wide" disabled={pending} onClick={remove}>Eliminar materia</button><button onClick={()=>setMode(null)}>Cancelar</button></div></>:<><h2>{mode==="add"?"Agregar materia":"Editar"}</h2><div className="crud-form"><input placeholder="Clave" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input placeholder="Nombre" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Coordinación" value={form.coordination} onChange={e=>setForm({...form,coordination:e.target.value})}/><div className="multi-wrap"><button className="multi-field" onClick={()=>setMulti(!multi)}><span>{form.careerIds.length?form.careerIds.map(id=>{const c=careers.find(x=>x.id===id);return <em key={id}>{c?.acronym}<span className="bx bxs-x" onClick={(e)=>{e.stopPropagation();toggle(id)}}></span></em>}):"Agrega carrera o carreras desde el menú multiselección"}</span><span className="bx bxs-grid-small"></span></button>{multi&&<div className="multi-menu">{careers.map(c=><button key={c.id} className={form.careerIds.includes(c.id)?"chosen":""} onClick={()=>toggle(c.id)}>{c.acronym}</button>)}</div>}</div><input type="number" min="1" max="12" placeholder="Semestre" value={form.semester} onChange={e=>setForm({...form,semester:Number(e.target.value)})}/></div><div className="form-actions"><button className="cancel-red" onClick={()=>setMode(null)}>Cancelar</button><button className="accept-green" disabled={pending} onClick={save}>Aceptar</button></div></>}</div></div>}
 </div>
}
